#!/usr/bin/env bash
# This script installs nginx

# carry a system update
apt update -y

# Install Nginx
apt -y install nginx

# Ensure Nginx is listening on port 80
ufw allow 'Nginx HTTP'

# Add "Hello, world!" to the html file
echo 'Hello World!' >/var/www/html/index

# make index.nginx-debian.html as the first file in the index directive
# sed -i 's/index.html index.htm;/index.nginx-debian.html index.html index.htm;/' /etc/nginx/sites-available/default

# restart nginx
/etc/init.d/nginx reload
