#!/usr/bin/env bash
# This script configures a Nginx server so that /redirect_me
# is redirecting to another page

# update apps
sudo apt-get -y update

# install nginx
sudo apt-get -y install nginx

# make nginx listen on port 80
sudo ufw allow 'Nginx HTTP'

sudo su <<EOF
echo "Hello World!" > /var/www/html/index.html;
EOF

# store configuration in a variable
config="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/huclark permanent;"

# configure redirection
sed -i "s/server_name _;/$config/" /etc/nginx/sites-enabled/default

# reload nginx
service nginx restart
