#!/usr/bin/env bash
#  Bash script containing commands to automatically configure a redirect
# on a new Ubuntu machine

sudo apt-get -y update
sudo apt-get install -y nginx

# Configure Nginx to listen on port 80
sudo ufw allow 'Nginx HTTP'

# start Nginx
sudo service nginx start

# With root priviledges, create a file with "Hello World!" message
sudo su <<DELIMETER
echo "Hello World!" > /var/www/html/index.html;
DELIMETER

# add permanent redirection
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/tami-cp0 permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

sudo service nginx restart
