#!/usr/bin/env bash
#  Bash script containing commands to automatically configure a redirect
# on a new Ubuntu machine

sudo apt-get -y update
sudo apt-get install -y nginx

# Configure Nginx to listen on port 80
sudo ufw allow 'Nginx HTTP'

# start Nginx
sudo service nginx start

# With root priviledges, create a file with "Hello World!" message
sudo su <<DELIMETER
echo "Hello World!" > /var/www/html/index.html;
DELIMETER

# add permanent redirection
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/huclark permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# Create a 404.html file with custom string
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# configure 404 page
custom_msg="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

# configure default page
sudo sed -i "s/listen 80 default_server;/$custom_msg/" /etc/nginx/sites-enabled/default

# restart nginx
sudo service nginx restart
