#!/usr/bin/env bash
# Configuring Nginx so that its HTTP response contains a
# custom header with the name, 'X-Served-By' and the
# value of the custom HTTP header must be the hostname of the 
# server Nginx is running on

sudo apt -y update
sudo apt -y install nginx

# configure nginx by adding the custom header
sudo sed -i "/http {/a\         add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf

sudo service nginx restart
