#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy

# start the service
sudo service haproxy start

# Configure HAproxy so that it send traffic to web-01 and web-02 using roundrobin
server1=$"492915-web-01"
server1_ip=$"54.157.167.117"
server2=$"492915-web-02"
server2_ip=$"54.160.75.58"

frontend_configuration=$"frontend http_front
    bind *:80
    default_backend http_back"

backend_configuration=$"backend http_back
    balance roundrobin
    server $server1 $server1_ip:80 check
    server $server2 $server2_ip:80 check"

sudo su << DELIMETER
    echo -e "\n$frontend_configuration\n$backend_configuration" >> /etc/haproxy/haproxy.cfg 
DELIMETER

sudo service haproxy restart
