#!/usr/bin/env bash
# This script displays a list of currently running processes
# Shows all processes, for all users, including those which might not have a TTY
# Displays in a user-oriented format
# Shows process hierarchy

ps aux --forest
