#!/usr/bin/env bash
# This script Creates the file /var/run/myscript.pid containing its PID
# Displays `To infinity and beyond` indefinitely
# Displays `I hate the kill command` when receiving a SIGTERM signal
# Displays `Y U no love me?!` when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when
# receiving a SIGQUIT or SIGTERM signal

# Specify the file to store the process ID (PID)
file=/var/run/myscript.pid

# Write the script's own PID to the specified file
echo $$ > "$file"

# Infinite loop
while true
do
	echo "To infinity and beyond"
	sleep 2

	# Define trap for SIGINT (Ctrl+C)
	trap 'echo "Y U no love me?!"' SIGINT

	# Define trap for SIGQUIT (Ctrl+\)
	trap 'rm $file; exit' SIGQUIT

	# Define trap for SIGTERM
	trap 'echo I hate the kill command; rm $file; exit' SIGTERM
done
