#!/usr/bin/env bash
# This script displays the content of the file `/etc/passwd`

# Path to the passwd file
passwd_file="/etc/passwd"

# Use a while loop to read each line of the passwd file
while IFS=":" read -r username _ uid gid info home_directory shell
do
	echo "The user $username is part of the $gid gang, lives in $home_directory and rides $shell. $uid's place is protected by the passcode x, more info about the user here: $info"
done < "$passwd_file"
