#!/usr/bin/env bash
# This script uses awk to group visitors by IP and HTTP status code
# and displays this data with the occurrence number

# Use awk to group visitors by IP and HTTP status code and count occurrences
awk ' { print $1,$9 } ' < apache-access.log | sort | uniq -c | sort -nr
