#!/usr/bin/env bash
# This script displays numbers from 1 to 20 and:
# displays `4` and then `bad luck from China` for the 4th loop iteration
# displays `9` and then `bad luck from Japan` for the 9th loop iteration
# displays `17` and then `bad luck from Italy` for the 17th loop iteration

i=0

while [ $i -lt 20 ]; do
	case $i in
		3)
			printf "4\nbad luck from China\n"
			;;
		8)
			printf "9\nbad luck from Japan\n"
			;;
		16)
			printf "17\nbad luck from Italy\n"
			;;
		*)
			echo $((i + 1))
		esac
		((i++))
done
