#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes:
# displays hours from 0 to 12
# displays minutes from 1 to 59

hour=0

# Iterate from 0 to 11 for hours
while [ $hour -lt 12 ]; do
	# Print the hour
	echo "Hour: $hour"

	# Initialize minute variable for innerloop
	minute=1

	# Iterate from 1 to 59 for minutes
	while [ $minute -lt 60 ]; do
		echo $minute
		((minute++))
	done

	((hour++))
done
