#!/usr/bin/env bash
# This script displays the content of the current directory
# in a list format
# where only the part of the name after the first dash is diaplayed

for file in *; do
	# Ensure all directories are ignored
	if [ -f "$file" ]; then
		# Extract the part of the name after the first dash
		name_after_dash=$(echo "$file" | cut -d '-' -f2-)

		# Print the modified file names
		echo "$name_after_dash"
	fi
done
