#!/usr/bin/env bash
# This script configures a server to setup a firewall to only allow
# incoming traffic from the following TCP ports:
# 22 (SSH)
# 443 (HTTPS SSL)
# 80 (HTTP)

sudo apt -y update
sudo apt -y install ufw
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw enable
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw status
