#!/usr/bin/env bash
# This scripts configures an ubuntu server;
# `localhost` resolves to `127.0.0.2`
# `facebook.com` resolves to `8.8.8.8`

# copy /etc/hosts contents to hosts.new file
cp /etc/hosts ~/hosts.new

# input `127.0.0.2 localhost` into the hosts.new
echo "127.0.0.2 localhost" > ~/hosts.new

# append "8.8.8.8  facebook.com" into hosts.new
echo "8.8.8.8  facebook.com" >> ~/hosts.new

# Forcefully overwrite the system's /etc/hosts with hosts.new
cp -f ~/hosts.new /etc/hosts
