#!/usr/bin/env bash
# script that configures the container to listen on port 8080 and run on nginx user.
sudo sed -i '1 s/#user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx restart
